"""Protocore — protocol-first core for small models (LLM agent orchestration).

Canonical import: ``from protocore import AgentOrchestrator, AgentConfig, ...``
"""
from __future__ import annotations

# Centralized constants
from .constants import (
    COMPACTION_SUMMARY_MARKER,
    DEFAULT_MODEL,
    LOAD_SKILL_TOOL_NAME,
    MANUAL_COMPACT_TOOL_NAME,
    MAX_ENVELOPE_PAYLOAD_CHARS,
    MAX_STRUCTURED_JSON_CHARS,
    PROTOCOL_VERSION,
    QWEN_NO_THINKING_EXTRA_BODY,
    SUBAGENT_CAPABILITY_SELECTION_PROMPT_TEMPLATE,
    ThinkingProfileRegistry,
)

# Public types
from .types import (
    AgentConfig,
    AgentContext,
    AgentEnvelope,
    AgentIdentity,
    AgentRole,
    ApiMode,
    CompactionSummary,
    CompressionEvent,
    ContentPart,
    ControlCommand,
    EnvelopeMeta,
    ExecutionMode,
    ExecutionReport,
    ExecutionStatus,
    LLMUsage,
    Message,
    MessageList,
    MessageType,
    PlanArtifact,
    PlanStep,
    PolicyDecision,
    Result,
    ResultPayload,
    RunKind,
    SkillIndexEntry,
    SkillLoadResult,
    SkillManifest,
    SkillTrustLevel,
    ShellAccessMode,
    ShellApprovalRule,
    ShellCommandPlan,
    ShellExecutionRequest,
    ShellExecutionResult,
    ShellSafetyMode,
    ShellToolConfig,
    ShellToolProfile,
    SessionSnapshot,
    StopReason,
    SubagentResult,
    SubagentRunSummary,
    SubagentStatus,
    ThinkingProfilePreset,
    ThinkingRunPolicy,
    ToolResultMeta,
    ToolCallRecord,
    ToolContextMeta,
    AgentContextMeta,
    attach_structured_usage,
    extract_structured_usage,
    get_text_content,
    TokenEstimateFunc,
    TokenEstimatorProfile,
    ToolContext,
    ToolDefinition,
    ToolParameterSchema,
    ToolResult,
    WorkflowDefinition,
    WorkflowEdge,
    WorkflowNode,
    WorkflowNodeStatus,
)

# Public protocols
from .protocols import (
    accumulate_usage_from_llm_calls,
    CapabilityBasedSelectionPolicy,
    CompressionStrategy,
    ExecutionPolicy,
    FirstAvailablePolicy,
    LLMClient,
    NoOpPlanningStrategy,
    OrchestrationStrategy,
    ParallelExecutionPolicy,
    PlanningPolicy,
    PlanningStrategy,
    RetryPolicy,
    ShellExecutor,
    ShellSafetyPolicy,
    SkillManager,
    StateManager,
    Storage,
    SubagentSelectionPolicy,
    TelemetryCollector,
    TimeoutPolicy,
    ToolExecutor,
    Transport,
    WorkflowEngine,
)
from .shell_handler import resume_from_pending

# Orchestrator
from .orchestrator import (
    AgentOrchestrator,
    ContractViolationError,
    ParallelSubagentRunner,
    run_bypass,
)

# Compression
from .compression import (
    ContextCompressor,
    auto_compact,
    manual_compact,
    micro_compact,
)

# Registry & factories
from .registry import AgentRegistry, StrategyRegistry, ToolRegistry
from .factories import (
    CoreFactory,
    make_agent_context,
    make_control_envelope,
    make_error_envelope,
    make_execution_report,
    make_load_skill_tool_definition,
    make_manual_compact_tool_definition,
    make_result_envelope,
    make_task_envelope,
    register_load_skill_tool,
    register_manual_compact_tool,
)
from .json_utils import structured_json_candidates

# Context helpers
from .context import (
    CancellationContext,
    PathIsolationError,
    build_tool_context,
    estimate_tokens,
    estimate_text_tokens,
    resolve_token_estimator,
    validate_path_access,
    validate_path_arguments,
)

# Events
from .events import (
    BusRegistry,
    CoreEvent,
    EventName,
    EV_CANCELLATION,
    EV_COMPRESSION_AUTO,
    EV_COMPRESSION_MANUAL,
    EV_COMPRESSION_MICRO,
    EV_DESTRUCTIVE_ACTION,
    EV_ERROR,
    EV_INJECTION_SIGNAL,
    EV_LLM_CALL_END,
    EV_LLM_CALL_START,
    EV_LOOP_ITERATION,
    EV_PLANNING_END,
    EV_PLANNING_START,
    EV_SESSION_END,
    EV_SESSION_START,
    EV_SKILL_BUDGET_EXCEEDED,
    EV_SKILL_INDEX_INJECTED,
    EV_SKILL_LOAD_END,
    EV_SKILL_LOAD_START,
    EV_SUBAGENT_END,
    EV_SUBAGENT_START,
    EV_TOOL_BUDGET_EXCEEDED,
    EV_TOOL_CALL_END,
    EV_TOOL_CALL_START,
    EV_WORKFLOW_END,
    EV_WORKFLOW_START,
    EventBus,
)

# Ingress
from .ingress import parse_envelope

# Hooks
from .hooks.manager import HookManager, create_plugin_manager
from .hooks.specs import AgentHookSpecs, hookimpl, hookspec

# LLM adapter (concrete implementation lives in integrations/llm/)
from .integrations.llm.openai_client import OpenAILLMClient
from .testing import FakeLLMClient

# Shell safety
from .shell_safety import DefaultShellSafetyPolicy

__version__ = "0.1.0"
__all__ = [
    "AgentConfig",
    "AgentContext",
    "AgentEnvelope",
    "AgentIdentity",
    "AgentRole",
    "ApiMode",
    "COMPACTION_SUMMARY_MARKER",
    "DEFAULT_MODEL",
    "MAX_ENVELOPE_PAYLOAD_CHARS",
    "MAX_STRUCTURED_JSON_CHARS",
    "PROTOCOL_VERSION",
    "QWEN_NO_THINKING_EXTRA_BODY",
    "SUBAGENT_CAPABILITY_SELECTION_PROMPT_TEMPLATE",
    "ThinkingProfileRegistry",
    "CompactionSummary",
    "CompressionEvent",
    "ContentPart",
    "ControlCommand",
    "EnvelopeMeta",
    "ExecutionMode",
    "ExecutionReport",
    "ExecutionStatus",
    "LLMUsage",
    "Message",
    "MessageList",
    "MessageType",
    "PlanArtifact",
    "PlanStep",
    "PolicyDecision",
    "Result",
    "ResultPayload",
    "RunKind",
    "SkillIndexEntry",
    "SkillLoadResult",
    "SkillManifest",
    "SkillTrustLevel",
    "ShellAccessMode",
    "ShellApprovalRule",
    "ShellCommandPlan",
    "ShellExecutionRequest",
    "ShellExecutionResult",
    "ShellSafetyMode",
    "ShellToolConfig",
    "ShellToolProfile",
    "SessionSnapshot",
    "StopReason",
    "SubagentResult",
    "SubagentRunSummary",
    "SubagentStatus",
    "ThinkingProfilePreset",
    "ThinkingRunPolicy",
    "ToolCallRecord",
    "TokenEstimateFunc",
    "TokenEstimatorProfile",
    "ToolContext",
    "ToolDefinition",
    "ToolParameterSchema",
    "ToolResult",
    "ToolResultMeta",
    "ToolContextMeta",
    "AgentContextMeta",
    "attach_structured_usage",
    "extract_structured_usage",
    "get_text_content",
    "WorkflowDefinition",
    "WorkflowEdge",
    "WorkflowNode",
    "WorkflowNodeStatus",
    "CompressionStrategy",
    "ExecutionPolicy",
    "FirstAvailablePolicy",
    "LLMClient",
    "NoOpPlanningStrategy",
    "CapabilityBasedSelectionPolicy",
    "OrchestrationStrategy",
    "ParallelExecutionPolicy",
    "PlanningPolicy",
    "PlanningStrategy",
    "RetryPolicy",
    "ShellExecutor",
    "ShellSafetyPolicy",
    "SkillManager",
    "StateManager",
    "Storage",
    "SubagentSelectionPolicy",
    "TelemetryCollector",
    "TimeoutPolicy",
    "ToolExecutor",
    "Transport",
    "WorkflowEngine",
    "accumulate_usage_from_llm_calls",
    "AgentOrchestrator",
    "ContractViolationError",
    "ParallelSubagentRunner",
    "run_bypass",
    "ContextCompressor",
    "auto_compact",
    "manual_compact",
    "micro_compact",
    "AgentRegistry",
    "CoreFactory",
    "LOAD_SKILL_TOOL_NAME",
    "MANUAL_COMPACT_TOOL_NAME",
    "StrategyRegistry",
    "ToolRegistry",
    "make_agent_context",
    "make_control_envelope",
    "make_error_envelope",
    "make_execution_report",
    "make_load_skill_tool_definition",
    "make_manual_compact_tool_definition",
    "make_result_envelope",
    "make_task_envelope",
    "register_load_skill_tool",
    "register_manual_compact_tool",
    "structured_json_candidates",
    "CancellationContext",
    "PathIsolationError",
    "build_tool_context",
    "estimate_tokens",
    "estimate_text_tokens",
    "resolve_token_estimator",
    "validate_path_access",
    "validate_path_arguments",
    "BusRegistry",
    "CoreEvent",
    "EV_CANCELLATION",
    "EV_COMPRESSION_AUTO",
    "EV_COMPRESSION_MANUAL",
    "EV_COMPRESSION_MICRO",
    "EV_DESTRUCTIVE_ACTION",
    "EV_ERROR",
    "EV_INJECTION_SIGNAL",
    "EV_LLM_CALL_END",
    "EV_LLM_CALL_START",
    "EV_LOOP_ITERATION",
    "EV_PLANNING_END",
    "EV_PLANNING_START",
    "EV_SESSION_END",
    "EV_SESSION_START",
    "EV_SKILL_BUDGET_EXCEEDED",
    "EV_SKILL_INDEX_INJECTED",
    "EV_SKILL_LOAD_END",
    "EV_SKILL_LOAD_START",
    "EV_SUBAGENT_END",
    "EV_SUBAGENT_START",
    "EV_TOOL_BUDGET_EXCEEDED",
    "EV_TOOL_CALL_END",
    "EV_TOOL_CALL_START",
    "EV_WORKFLOW_END",
    "EV_WORKFLOW_START",
    "EventBus",
    "EventName",
    "parse_envelope",
    "AgentHookSpecs",
    "HookManager",
    "create_plugin_manager",
    "hookimpl",
    "hookspec",
    "OpenAILLMClient",
    "FakeLLMClient",
    "DefaultShellSafetyPolicy",
    "resume_from_pending",
    "__version__",
]
